<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework
 *
 * **********************************************************************************************
 *
 * Copyright (c) 2009 phoebius.org
 *
 * This program is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 3 of the License, or (at your option) any later version.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program; if not, see <http://www.gnu.org/licenses/>.
 *
 ************************************************************************************************/

/**
 * @ingroup Orm_Domain_CodeGenerator
 */
abstract class CodeConstructor
{
	/**
	 * @return void
	 */
	abstract function make(IOutput $ws);

	/**
	 * @return string
	 */
	protected function getFileHeader($message = 'This is file is autogenerated')
	{
		return <<<EOT
<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * {$message}
 *
 ************************************************************************************************/


EOT;
	}

	/**
	 * @return string
	 */
	protected function getFileFooter()
	{
		return <<<EOT


?>
EOT;
	}
}

?>