<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework
 *
 * **********************************************************************************************
 *
 * Copyright notice
 *
 ************************************************************************************************/

/**
 * @ingroup OrmCodeGenerator
 */
abstract class CodeConstructor
{
	/**
	 * @return void
	 */
	abstract function make(IWriteStream $ws);

	/**
	 * @return string
	 */
	protected function getFileHeader($message = 'This is file is autogenerated')
	{
		return <<<EOT
<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * {$message}
 *
 ************************************************************************************************/


EOT;
	}

	/**
	 * @return string
	 */
	protected function getFileFooter()
	{
		return <<<EOT


?>
EOT;
	}
}

?>