<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework
 *
 * **********************************************************************************************
 *
 * Copyright notice
 *
 ************************************************************************************************/

/**
 * @ingroup OrmModel
 */
final class OrmPropertyVisibility extends Enumeration
{
	/**
	 * Getter + setter
	 */
	const FULL = 'full';

	/**
	 * Only getter (for db columns generated by triggers, and so on)
	 */
	const READONLY = 'readonly';

	/**
	 * Nothing (for db columns that used for inner calculations via triggers in denormalized
	 * database schemas)
	 */
	const TRANSPARENT = 'transparent';

	static private $gettable = array(
		self::FULL, self::READONLY
	);

	static private $settable = array(
		self::FULL
	);

	/**
	 * @return OrmPropertyVisibility
	 */
	static function full()
	{
		return new self (self::FULL);
	}

	/**
	 * @return OrmPropertyVisibility
	 */
	static function readonly()
	{
		return new self (self::READONLY);
	}

	/**
	 * @return OrmPropertyVisibility
	 */
	static function transparent()
	{
		return new self (self::TRANSPARENT);
	}

	/**
	 * @return boolean
	 */
	function isGettable()
	{
		return in_array($this->getValue(), self::$gettable);
	}

	/**
	 * @return boolean
	 */
	function isSettable()
	{
		return in_array($this->getValue(), self::$settable);
	}
}

?>