<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework
 *
 * **********************************************************************************************
 *
 * Copyright (c) 2009 phoebius.org
 *
 * This program is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 3 of the License, or (at your option) any later version.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program; if not, see <http://www.gnu.org/licenses/>.
 *
 ************************************************************************************************/

/**
 * @ingroup Orm_Model
 */
final class OrmPropertyVisibility extends Enumeration
{
	/**
	 * Getter + setter
	 */
	const FULL = 'full';

	/**
	 * Only getter (for db columns generated by triggers, and so on)
	 */
	const READONLY = 'readonly';

	/**
	 * Nothing (for db columns that used for inner calculations via triggers in denormalized
	 * database schemas)
	 */
	const TRANSPARENT = 'transparent';

	static private $gettable = array(
		self::FULL, self::READONLY
	);

	static private $settable = array(
		self::FULL
	);

	/**
	 * @return OrmPropertyVisibility
	 */
	static function full()
	{
		return new self (self::FULL);
	}

	/**
	 * @return OrmPropertyVisibility
	 */
	static function readonly()
	{
		return new self (self::READONLY);
	}

	/**
	 * @return OrmPropertyVisibility
	 */
	static function transparent()
	{
		return new self (self::TRANSPARENT);
	}

	/**
	 * @return boolean
	 */
	function isGettable()
	{
		return in_array($this->getValue(), self::$gettable);
	}

	/**
	 * @return boolean
	 */
	function isSettable()
	{
		return in_array($this->getValue(), self::$settable);
	}
}

?>